const defaultSetting = {
  letterSize: "22",
  bold: "false",
  typography: "Send Flowers",
  letterColor: "#efe6e6",
  backgroundColor: "#474343",
  marginRow: "10",
  marginSet: "4",
  marginTop: "18",
  marginLeft: "18",
  borderTop: "false",
  borderBottom: "true",
  borderRight: "false",
  borderLeft: "false",
  borderStyle: "solid",
  borderColor: "#ece02c",
  initialPPM: "350",
  finalPPM: "500",
  increasePPM: "10",
  increasePagePPM: "2",
  row: "8",
  set: "3",
  wordSet: "6",
  lineBreakTab: "true",
};

export { defaultSetting };
