const defaultSetting = {
  letterSize: "25",
  bold: "false",
  typography: "Send Flowers",
  letterColor: "#efe6e6",
  lineBreakTab: "true",
  backgroundColor: "#474343",
  marginRow: "1",
  marginSet: "1",
  marginTop: "5",
  marginLeft: "5",
  borderTop: "false",
  borderBottom: "true",
  borderRight: "false",
  borderLeft: "false",
  borderStyle: "solid",
  borderColor: "#ece02c",
  ppmInitial: "300",
  ppmFinal: "500",
  ppmIncrease: "10",
  ppmIncreasePage: "2",
  row: "3",
  set: "3",
  setWord: "3",
};

export { defaultSetting };
